### ISSUE TITLE
How to get best performance installation on AMD EPYC 7773X 64-Core Processor? 

### ISSUE THREAD

**Issue by 2catycm** [amd/amd-fftw#10]
I am using spack, with the instruction on https://developer.amd.com/spack/amd-optimized-cpu-libraries/.
However, I don't know what is "threads"

**Comment by BiplabRaut** [comment]
Hi, 
The "threads" option enables the compilation of the threaded FFTW library.
You can compile the library with either of the two options:
threads=on   : It will use posix threads on unix and win32 on windows
openmp=on : It will use OpenMP threads.

Thanks.
