### ISSUE TITLE
Trying to mkdir -p /include

### ISSUE THREAD

**Issue by chrisreidy** [amd/amd-fftw#6]
The build is going nicely through "Making install in api" section, and then this:
 /usr/bin/mkdir -p '/include'
/usr/bin/mkdir: cannot create directory ‘/include’: Permission denied.
Is there an unwanted / ?

My options are:
./configure --prefix=${InstallRoot} --enable-sse2 --enable-avx --enable-avx2 --enable-mpi --enable-openmp --enable-shared --enable-amd-opt --enable-amd-mpifft

**Comment by BiplabRaut** [comment]
Hi,
    It seems the problem is due to the value of ${InstallRoot}.
Could you please check what is its value? Is the value of ${InstallRoot} NULL?
The command "make install" would fail if ${InstallRoot} is set to a path for which the user does not have permission.

Thanks,
S. Biplab Raut

**Comment by chrisreidy** [comment]
My install script uses the variable to simplify references to the install location, but other parts of this build don't pick that up so changing to the absolute path worked.
/usr/bin/mkdir -p '/opt/ohpc/pub/apps/aocl-fftw/2.2/include'
Thanks
