### ISSUE TITLE
Missing fftw3f.dll with AOCL release v3

### ISSUE THREAD

**Issue by shehrzad** [amd/amd-fftw#8]
I am attempting to use this library on Windows 10 with Visual Studio 2019. I downloaded the prebuilt Windows version from [the AMD Optimizing CPU Libraries](https://developer.amd.com/amd-aocl/) page. My code #defines FFTW_DLL prior to #including "fftw3.h". My build configuration is x64, and I copy all of the DLLs in the package into the working directory.

When I run my executable I get an error message: "The code execution cannot proceed because fftw3f.dll was not found."

There is no such DLL in the aforementioned package, and I'm surprised because that DLL seems to be from the standard (non-AMD optimized) FFTW distro. The DLLs in the "Zen2" directory are:

```
$ ls -l *.dll
-rwxr-xr-x 1 shehr 197609 6041240 Mar 12 09:23 libfftw-dll.dll*
-rwxr-xr-x 1 shehr 197609 7379104 Mar 12 09:23 libfftwf-dll.dll*
-rwxr-xr-x 1 shehr 197609 7456936 Mar 12 09:23 libfftwf-mpi-dll.dll*
-rwxr-xr-x 1 shehr 197609 7390888 Mar 12 09:23 libfftwf-omp-dll.dll*
-rwxr-xr-x 1 shehr 197609  939168 Mar 12 09:23 libfftwl-dll.dll*
-rwxr-xr-x 1 shehr 197609 1018024 Mar 12 09:23 libfftwl-mpi-dll.dll*
-rwxr-xr-x 1 shehr 197609  950952 Mar 12 09:23 libfftwl-omp-dll.dll*
-rwxr-xr-x 1 shehr 197609 6119072 Mar 12 09:23 libfftw-mpi-dll.dll*
-rwxr-xr-x 1 shehr 197609 6052512 Mar 12 09:23 libfftw-omp-dll.dll*
-rwxr-xr-x 1 shehr 197609  660112 Mar 12 09:23 libomp.dll*
```

**Comment by SivaramanSuresh** [comment]
Hi @shehrzad, 
It looks like your application is coded to link with "fftw3f.dll" at run time. AOCL Windows libraries have used a slightly different naming format for the libraries, ("libfftwf-dll.dll" in this case).

Kindly update the code in your application to use "libfftwf-dll.dll" from the AOCL prebuilt Windows library and re-build the application.

If you face any issues in using these libraries, you could reach out to us on "toolchainsupport@amd.com".

Regards,
Suresh S
AOCL Team, 
AMD India Pvt Ltd

**Comment by BiplabRaut** [comment]
I hope the issue is resolved. Closing this thread.
